In [1]:
import os
import pandas as pd
import re

In [2]:
directorio_raw = './data/raw'  # Reemplaza esto con la ruta de tu directorio

# Verifica si el directorio existe
if os.path.exists(directorio_raw) and os.path.isdir(directorio_raw):
    archivos = os.listdir(directorio_raw)
    if archivos:
        print("Archivos en el directorio:")
        for archivo in archivos[:1]:
            print(archivo)
            path = directorio_raw+'/'+archivo
            df = pd.read_excel(path,header=9)#, usecols="B:") 
    else:
        print("El directorio está vacío.")
else:
    print("El directorio no existe o no es válido.")

Archivos en el directorio:
MAFEBA.xlsx

In [3]:
df.rename(columns={'Unnamed: 1': 'codigo', 'Unnamed: 3': 'descripcion', 'Unnamed: 26': 'precio_unitario', 'Unnamed: 29': 'variacion'}, inplace=True)
columnas_a_eliminar_1 = ['Unnamed: ' + str(i) for i in range(4, 26)] 
columnas_a_eliminar_2 = ['Unnamed: ' + str(i) for i in range(27, 29)] 
columnas_a_eliminar_3 = ['Unnamed: 0','Unnamed: 2'] 

# Combina las tres listas en una sola
columnas_a_eliminar = columnas_a_eliminar_1 + columnas_a_eliminar_2 + columnas_a_eliminar_3
df.drop(columns=columnas_a_eliminar, inplace=True)
df = df.dropna(subset=['precio_unitario'])

# Crear una expresión regular para identificar las filas donde 'codigo' contiene texto
patron = r'.*[a-zA-Z].*'

# Filtrar las filas que cumplen con el patrón y eliminarlas
df = df[~df['codigo'].str.contains(patron, na=False)]
df = df[~df['precio_unitario'].str.contains(patron, na=False)]
df['precio'] = df['precio_unitario']*(1+df['variacion'])

In [4]:
df

,codigo,descripcion,precio_unitario,variacion,precio
21,0271,ASIENTO ALMA BRONCE & GOMA SLOAN,1373.4,0,1373.4
22,0272,ASIENTO ALMA BRONCE & GOMA DIOGENES,1373.4,0,1373.4
24,0045,ARANDELA BRONCE TORNILLO FV,30.2,0.391705,42.029493
25,0046,ARANDELA BRONCE TORNILLO PEIRANO,30.2,0.391705,42.029493
26,0047,ARANDELA BRONCE BULON TAPA CAMARA,86,0.116883,96.051948
...,...,...,...,...,...
547,0298,VALVULA CANILLA ALARGUE SILICONA,164.4,0.030721,169.450533
549,0179,VALVULA TRANSFERENCIA PEIRANO BIDET TODO GOMA,43.6,0.081886,47.170223
552,6060,VENTOSA GOMA DESTAPA CAÑERIAS CHICA ECONOMICA,276.7,0,276.7
553,6061,VENTOSA GOMA DESTAPA CAÑERIAS CHICA,346.7,0,346.7
554,6062,VENTOSA GOMA DESTAPA CAÑERIAS GIGANTE,516.7,0,516.7

In [5]:
directorio_out = './data/out/'+archivo
df.to_excel(directorio_out)